[project]
name = "fakenews-gca"
version = "0.1.0"
description = "Fake news detection with GCA"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "annotated-types",
    "anyio",
    "certifi",
    "charset-normalizer",
    "click",
    "contourpy",
    "cycler",
    "distro",
    "exceptiongroup",
    "filelock",
    "fonttools",
    "fsspec",
    "h11",
    "hf-xet",
    "httpcore",
    "httpx",
    "huggingface-hub",
    "idna",
    "jieba",
    "Jinja2",
    "jiter",
    "joblib",
    "kiwisolver",
    "MarkupSafe",
    "matplotlib",
    "mpmath",
    "networkx",
    "nltk",
    "numpy",
    "nvitop",
    "openai",
    "packaging",
    "pandas",
    "pillow",
    "protobuf",
    "psutil",
    "pydantic",
    "pydantic_core",
    "pyparsing",
    "python-dateutil",
    "pytz",
    "PyYAML",
    "regex",
    "requests",
    "safetensors",
    "scikit-learn",
    "scipy",
    "seaborn",
    "six",
    "sniffio",
    "torch",
    "transformers<5",
]
